# Generated by Django 4.1.2 on 2022-10-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('released', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
